const CHUNKS = [
  { id:"c1", lv:1, es:"por favor", de:"bitte", ex:"Un café, por favor.", exde:"Einen Kaffee, bitte." },
  { id:"c2", lv:1, es:"de nada", de:"gern geschehen", ex:"—Gracias. —De nada.", exde:"—Danke. —Gern geschehen." },
  { id:"c3", lv:1, es:"mucho gusto", de:"freut mich", ex:"Mucho gusto, soy Ana.", exde:"Freut mich, ich bin Ana." },
  { id:"c4", lv:1, es:"¿qué tal?", de:"wie geht’s?", ex:"Hola, ¿qué tal?", exde:"Hallo, wie geht’s?" },
  { id:"c5", lv:1, es:"¿cómo estás?", de:"wie geht’s dir?", ex:"¿Cómo estás hoy?", exde:"Wie geht’s dir heute?" },
  { id:"c6", lv:1, es:"estoy bien", de:"mir geht’s gut", ex:"Estoy bien, gracias.", exde:"Mir geht’s gut, danke." },
  { id:"c7", lv:1, es:"no entiendo", de:"ich verstehe nicht", ex:"Perdón, no entiendo.", exde:"Entschuldigung, ich verstehe nicht." },
  { id:"c8", lv:1, es:"más despacio", de:"langsamer", ex:"Habla más despacio, por favor.", exde:"Sprich bitte langsamer." },
  { id:"c9", lv:1, es:"¿puedes repetir?", de:"kannst du das wiederholen?", ex:"¿Puedes repetir, por favor?", exde:"Kannst du das bitte wiederholen?" },
  { id:"c10", lv:1, es:"no sé", de:"ich weiß nicht", ex:"No sé qué decir.", exde:"Ich weiß nicht, was ich sagen soll." },
  { id:"c11", lv:1, es:"por supuesto", de:"natürlich", ex:"Por supuesto que sí.", exde:"Natürlich." },
  { id:"c12", lv:1, es:"ahora mismo", de:"sofort / genau jetzt", ex:"Voy ahora mismo.", exde:"Ich gehe sofort." },
  { id:"c13", lv:1, es:"un momento", de:"einen Moment", ex:"Un momento, por favor.", exde:"Einen Moment, bitte." },
  { id:"c14", lv:1, es:"¿cuánto cuesta?", de:"wie viel kostet das?", ex:"¿Cuánto cuesta esto?", exde:"Wie viel kostet das?" },
  { id:"c15", lv:1, es:"la cuenta, por favor", de:"die Rechnung, bitte", ex:"La cuenta, por favor.", exde:"Die Rechnung, bitte." },
  { id:"c16", lv:1, es:"¿dónde está el baño?", de:"wo ist die Toilette?", ex:"¿Dónde está el baño?", exde:"Wo ist die Toilette?" },
  { id:"c17", lv:1, es:"soy de Alemania", de:"ich komme aus Deutschland", ex:"Soy de Alemania.", exde:"Ich komme aus Deutschland." },
  { id:"c18", lv:1, es:"me llamo…", de:"ich heiße…", ex:"Me llamo Benedikt.", exde:"Ich heiße Benedikt." },
  { id:"c19", lv:1, es:"mucho / un poco", de:"viel / ein bisschen", ex:"Hablo un poco de español.", exde:"Ich spreche ein bisschen Spanisch." },
  { id:"c20", lv:1, es:"hasta luego", de:"bis später", ex:"Hasta luego, nos vemos.", exde:"Bis später, wir sehen uns." },
  { id:"c21", lv:1, es:"nos vemos", de:"wir sehen uns", ex:"Nos vemos mañana.", exde:"Wir sehen uns morgen." },
  { id:"c22", lv:1, es:"lo siento", de:"es tut mir leid", ex:"Lo siento, llego tarde.", exde:"Tut mir leid, ich komme zu spät." },
  { id:"c23", lv:1, es:"no pasa nada", de:"kein Problem / nichts passiert", ex:"—Perdón. —No pasa nada.", exde:"—Entschuldigung. —Kein Problem." },
  { id:"c24", lv:1, es:"está bien", de:"ist in Ordnung", ex:"Sí, está bien.", exde:"Ja, ist in Ordnung." },
  { id:"c25", lv:1, es:"tengo hambre", de:"ich habe Hunger", ex:"Tengo hambre.", exde:"Ich habe Hunger." },
  { id:"c26", lv:1, es:"tengo sed", de:"ich habe Durst", ex:"Tengo sed.", exde:"Ich habe Durst." },
  { id:"c27", lv:1, es:"tengo que…", de:"ich muss…", ex:"Tengo que trabajar.", exde:"Ich muss arbeiten." },
  { id:"c28", lv:1, es:"quiero…", de:"ich möchte…", ex:"Quiero agua, por favor.", exde:"Ich möchte Wasser, bitte." },
  { id:"c29", lv:1, es:"me gusta…", de:"ich mag…", ex:"Me gusta el café.", exde:"Ich mag Kaffee." },
  { id:"c30", lv:1, es:"hay…", de:"es gibt…", ex:"Hay un problema.", exde:"Es gibt ein Problem." },
  { id:"c31", lv:2, es:"¿me puedes ayudar?", de:"kannst du mir helfen?", ex:"¿Me puedes ayudar?", exde:"Kannst du mir helfen?" },
  { id:"c32", lv:2, es:"estoy buscando…", de:"ich suche…", ex:"Estoy buscando la estación.", exde:"Ich suche den Bahnhof." },
  { id:"c33", lv:2, es:"¿cómo llego a…?", de:"wie komme ich zu…?", ex:"¿Cómo llego al centro?", exde:"Wie komme ich ins Zentrum?" },
  { id:"c34", lv:2, es:"está cerca / lejos", de:"es ist nah / weit", ex:"El hotel está cerca.", exde:"Das Hotel ist in der Nähe." },
  { id:"c35", lv:2, es:"a la derecha", de:"rechts", ex:"Gira a la derecha.", exde:"Bieg rechts ab." },
  { id:"c36", lv:2, es:"a la izquierda", de:"links", ex:"Está a la izquierda.", exde:"Es ist links." },
  { id:"c37", lv:2, es:"todo recto", de:"geradeaus", ex:"Sigue todo recto.", exde:"Geh geradeaus weiter." },
  { id:"c38", lv:2, es:"¿tiene wifi?", de:"gibt es WLAN?", ex:"¿Tiene wifi, por favor?", exde:"Gibt es WLAN, bitte?" },
  { id:"c39", lv:2, es:"¿puedo pagar con tarjeta?", de:"kann ich mit Karte zahlen?", ex:"¿Puedo pagar con tarjeta?", exde:"Kann ich mit Karte zahlen?" },
  { id:"c40", lv:2, es:"está abierto / cerrado", de:"es ist offen / geschlossen", ex:"Hoy está cerrado.", exde:"Heute ist geschlossen." },
  { id:"c41", lv:2, es:"quedamos a las…", de:"wir treffen uns um…", ex:"¿Quedamos a las cinco?", exde:"Treffen wir uns um fünf?" },
  { id:"c42", lv:2, es:"te llamo luego", de:"ich rufe dich später an", ex:"Te llamo luego.", exde:"Ich rufe dich später an." },
  { id:"c43", lv:2, es:"¿qué hora es?", de:"wie spät ist es?", ex:"¿Qué hora es?", exde:"Wie spät ist es?" },
  { id:"c44", lv:2, es:"tengo una reserva", de:"ich habe eine Reservierung", ex:"Tengo una reserva a nombre de…", exde:"Ich habe eine Reservierung auf den Namen…" },
  { id:"c45", lv:2, es:"una habitación para dos", de:"ein Zimmer für zwei", ex:"Una habitación para dos, por favor.", exde:"Ein Zimmer für zwei, bitte." },
  { id:"c46", lv:2, es:"me duele…", de:"mir tut … weh", ex:"Me duele la cabeza.", exde:"Mir tut der Kopf weh." },
  { id:"c47", lv:2, es:"necesito ayuda", de:"ich brauche Hilfe", ex:"Necesito ayuda, por favor.", exde:"Ich brauche Hilfe, bitte." },
  { id:"c48", lv:2, es:"estoy perdido/a", de:"ich habe mich verlaufen", ex:"Estoy perdido, ¿dónde está la plaza?", exde:"Ich habe mich verlaufen, wo ist der Platz?" },
  { id:"c49", lv:2, es:"voy a…", de:"ich werde / ich gehe…", ex:"Voy a estudiar.", exde:"Ich werde lernen." },
  { id:"c50", lv:2, es:"me encanta…", de:"ich liebe / mag sehr…", ex:"Me encanta España.", exde:"Ich liebe Spanien." },
  { id:"c51", lv:2, es:"da igual", de:"ist egal", ex:"Me da igual.", exde:"Ist mir egal." },
  { id:"c52", lv:2, es:"de acuerdo", de:"einverstanden", ex:"De acuerdo, vamos.", exde:"Einverstanden, los." },
  { id:"c53", lv:2, es:"claro que sí", de:"klar / natürlich", ex:"Claro que sí.", exde:"Klar doch." },
  { id:"c54", lv:2, es:"otra vez", de:"noch einmal", ex:"Otra vez, por favor.", exde:"Noch einmal, bitte." },
  { id:"c55", lv:3, es:"tengo ganas de…", de:"ich habe Lust auf…", ex:"Tengo ganas de viajar.", exde:"Ich habe Lust zu reisen." },
  { id:"c56", lv:3, es:"acabo de…", de:"ich habe gerade…", ex:"Acabo de llegar.", exde:"Ich bin gerade angekommen." },
  { id:"c57", lv:3, es:"estoy a punto de…", de:"ich bin gerade dabei zu…", ex:"Estoy a punto de salir.", exde:"Ich bin gerade dabei zu gehen." },
  { id:"c58", lv:3, es:"no te preocupes", de:"mach dir keine Sorgen", ex:"No te preocupes, está bien.", exde:"Mach dir keine Sorgen, es ist okay." },
  { id:"c59", lv:3, es:"¿te importa si…?", de:"stört es dich, wenn…?", ex:"¿Te importa si abro la ventana?", exde:"Stört es dich, wenn ich das Fenster öffne?" },
  { id:"c60", lv:3, es:"me parece bien", de:"das finde ich gut", ex:"Me parece bien.", exde:"Das finde ich gut." },
  { id:"c61", lv:3, es:"tiene sentido", de:"ergibt Sinn", ex:"Sí, tiene sentido.", exde:"Ja, das ergibt Sinn." },
  { id:"c62", lv:3, es:"por eso", de:"deshalb", ex:"Estoy cansado, por eso me quedo.", exde:"Ich bin müde, deshalb bleibe ich." },
  { id:"c63", lv:3, es:"sin embargo", de:"jedoch", ex:"Es difícil, sin embargo lo intento.", exde:"Es ist schwer, trotzdem versuche ich es." },
  { id:"c64", lv:3, es:"en mi opinión", de:"meiner Meinung nach", ex:"En mi opinión, es mejor esperar.", exde:"Meiner Meinung nach ist Warten besser." },
  { id:"c65", lv:3, es:"de vez en cuando", de:"ab und zu", ex:"Viajo de vez en cuando.", exde:"Ich reise ab und zu." },
  { id:"c66", lv:3, es:"a menudo", de:"oft", ex:"Practico a menudo.", exde:"Ich übe oft." },
  { id:"c67", lv:3, es:"cuanto antes", de:"so bald wie möglich", ex:"Llámame cuanto antes.", exde:"Ruf mich so bald wie möglich an." },
  { id:"c68", lv:3, es:"está lloviendo", de:"es regnet", ex:"Está lloviendo mucho.", exde:"Es regnet stark." },
  { id:"c69", lv:3, es:"hace calor / frío", de:"es ist heiß / kalt", ex:"Hoy hace calor.", exde:"Heute ist es heiß." },
  { id:"c70", lv:3, es:"me gustaría…", de:"ich würde gern…", ex:"Me gustaría un té.", exde:"Ich hätte gern einen Tee." },
  { id:"c71", lv:3, es:"¿podrías…?", de:"könntest du…?", ex:"¿Podrías ayudarme?", exde:"Könntest du mir helfen?" },
  { id:"c72", lv:3, es:"da igual, da lo mismo", de:"egal / dasselbe", ex:"Me da lo mismo.", exde:"Ist mir egal." },
  { id:"c73", lv:4, es:"ojalá…", de:"hoffentlich…", ex:"Ojalá haga buen tiempo.", exde:"Hoffentlich ist das Wetter gut." },
  { id:"c74", lv:4, es:"aunque…", de:"obwohl / auch wenn…", ex:"Aunque esté cansado, salgo.", exde:"Auch wenn ich müde bin, gehe ich raus." },
  { id:"c75", lv:4, es:"cuando llegue…", de:"wenn ich ankomme…", ex:"Cuando llegue, te llamo.", exde:"Wenn ich ankomme, rufe ich dich an." },
  { id:"c76", lv:4, es:"no creo que…", de:"ich glaube nicht, dass…", ex:"No creo que llueva.", exde:"Ich glaube nicht, dass es regnet." },
  { id:"c77", lv:4, es:"es importante que…", de:"es ist wichtig, dass…", ex:"Es importante que estudies.", exde:"Es ist wichtig, dass du lernst." },
  { id:"c78", lv:4, es:"en absoluto", de:"überhaupt nicht", ex:"No me gusta en absoluto.", exde:"Das mag ich überhaupt nicht." },
  { id:"c79", lv:4, es:"tal vez / quizá", de:"vielleicht", ex:"Quizá vaya mañana.", exde:"Vielleicht gehe ich morgen." },
  { id:"c80", lv:4, es:"se puede…", de:"man kann…", ex:"¿Se puede pagar aquí?", exde:"Kann man hier zahlen?" }
];
