const LEVELS = [
  { id: 1, name: "Nivel 1", words: 100, subtitle: "Die 100 wichtigsten Wörter" },
  { id: 2, name: "Nivel 2", words: 200, subtitle: "Die 200 wichtigsten Wörter" },
  { id: 3, name: "Nivel 3", words: 350, subtitle: "Die 350 wichtigsten Wörter" },
  { id: 4, name: "Nivel 4", words: 500, subtitle: "Die 500 wichtigsten Wörter" }
];

const POS_DE = {
  n: "Nomen",
  v: "Verb",
  adj: "Adjektiv",
  adv: "Adverb",
  prep: "Präposition",
  pron: "Pronomen",
  conj: "Konjunktion",
  intj: "Ausdruck",
  art: "Artikel",
  num: "Zahl",
  phr: "Wendung"
};

const VOCAB = [
  { id:"v1", lv:1, es:"hola", de:"hallo", pos:"intj", ex:"¡Hola! ¿Qué tal?", exde:"Hallo! Wie geht’s?" },
  { id:"v2", lv:1, es:"adiós", de:"auf Wiedersehen", pos:"intj", ex:"Adiós, hasta mañana.", exde:"Tschüss, bis morgen." },
  { id:"v3", lv:1, es:"gracias", de:"danke", pos:"intj", ex:"Muchas gracias.", exde:"Vielen Dank." },
  { id:"v4", lv:1, es:"por favor", de:"bitte", pos:"phr", ex:"Un café, por favor.", exde:"Einen Kaffee, bitte." },
  { id:"v5", lv:1, es:"sí", de:"ja", pos:"adv", ex:"Sí, claro.", exde:"Ja, klar." },
  { id:"v6", lv:1, es:"no", de:"nein / nicht", pos:"adv", ex:"No, gracias.", exde:"Nein, danke." },
  { id:"v7", lv:1, es:"buenos días", de:"guten Morgen / Tag", pos:"intj", ex:"Buenos días, Ana.", exde:"Guten Morgen, Ana." },
  { id:"v8", lv:1, es:"buenas tardes", de:"guten Tag / Abend", pos:"intj", ex:"Buenas tardes a todos.", exde:"Guten Tag allerseits." },
  { id:"v9", lv:1, es:"buenas noches", de:"gute Nacht / guten Abend", pos:"intj", ex:"Buenas noches, hasta mañana.", exde:"Gute Nacht, bis morgen." },
  { id:"v10", lv:1, es:"perdón", de:"Entschuldigung", pos:"intj", ex:"Perdón, ¿dónde está el baño?", exde:"Entschuldigung, wo ist die Toilette?" },
  { id:"v11", lv:1, es:"de nada", de:"gern geschehen", pos:"phr", ex:"—Gracias. —De nada.", exde:"—Danke. —Gern geschehen." },
  { id:"v12", lv:1, es:"vale", de:"okay / in Ordnung", pos:"intj", ex:"Vale, nos vemos.", exde:"Okay, wir sehen uns." },
  { id:"v13", lv:1, es:"hay", de:"es gibt", pos:"v", ex:"Hay un problema.", exde:"Es gibt ein Problem." },
  { id:"v14", lv:1, es:"yo", de:"ich", pos:"pron", ex:"Yo soy de Alemania.", exde:"Ich komme aus Deutschland." },
  { id:"v15", lv:1, es:"tú", de:"du", pos:"pron", ex:"¿Tú hablas español?", exde:"Sprichst du Spanisch?" },
  { id:"v16", lv:1, es:"él", de:"er", pos:"pron", ex:"Él es mi hermano.", exde:"Er ist mein Bruder." },
  { id:"v17", lv:1, es:"ella", de:"sie (Singular)", pos:"pron", ex:"Ella vive en Madrid.", exde:"Sie wohnt in Madrid." },
  { id:"v18", lv:1, es:"nosotros", de:"wir", pos:"pron", ex:"Nosotros estamos bien.", exde:"Uns geht es gut." },
  { id:"v19", lv:1, es:"vosotros", de:"ihr (Spanien)", pos:"pron", ex:"¿Vosotros sois estudiantes?", exde:"Seid ihr Studenten?" },
  { id:"v20", lv:1, es:"ellos", de:"sie (Plural, m.)", pos:"pron", ex:"Ellos trabajan aquí.", exde:"Sie arbeiten hier." },
  { id:"v21", lv:1, es:"usted", de:"Sie (höflich)", pos:"pron", ex:"¿Cómo se llama usted?", exde:"Wie heißen Sie?" },
  { id:"v22", lv:1, es:"me", de:"mich / mir", pos:"pron", ex:"Me llamo Luis.", exde:"Ich heiße Luis." },
  { id:"v23", lv:1, es:"te", de:"dich / dir", pos:"pron", ex:"Te quiero.", exde:"Ich liebe dich. / Ich mag dich." },
  { id:"v24", lv:1, es:"el", de:"der (m.)", pos:"art", ex:"El libro es nuevo.", exde:"Das Buch ist neu." },
  { id:"v25", lv:1, es:"la", de:"die (f.)", pos:"art", ex:"La casa es grande.", exde:"Das Haus ist groß." },
  { id:"v26", lv:1, es:"los", de:"die (m. Plural)", pos:"art", ex:"Los niños juegan.", exde:"Die Kinder spielen." },
  { id:"v27", lv:1, es:"las", de:"die (f. Plural)", pos:"art", ex:"Las mesas están llenas.", exde:"Die Tische sind voll." },
  { id:"v28", lv:1, es:"un", de:"ein (m.)", pos:"art", ex:"Un café, por favor.", exde:"Einen Kaffee, bitte." },
  { id:"v29", lv:1, es:"una", de:"eine (f.)", pos:"art", ex:"Una pregunta.", exde:"Eine Frage." },
  { id:"v30", lv:1, es:"mi", de:"mein / meine", pos:"pron", ex:"Mi nombre es Sara.", exde:"Mein Name ist Sara." },
  { id:"v31", lv:1, es:"tu", de:"dein / deine", pos:"pron", ex:"¿Dónde está tu casa?", exde:"Wo ist dein Haus?" },
  { id:"v32", lv:1, es:"qué", de:"was", pos:"pron", ex:"¿Qué es esto?", exde:"Was ist das?" },
  { id:"v33", lv:1, es:"quién", de:"wer", pos:"pron", ex:"¿Quién es ella?", exde:"Wer ist sie?" },
  { id:"v34", lv:1, es:"dónde", de:"wo", pos:"adv", ex:"¿Dónde vives?", exde:"Wo wohnst du?" },
  { id:"v35", lv:1, es:"cuándo", de:"wann", pos:"adv", ex:"¿Cuándo llegas?", exde:"Wann kommst du an?" },
  { id:"v36", lv:1, es:"por qué", de:"warum", pos:"adv", ex:"¿Por qué estudias español?", exde:"Warum lernst du Spanisch?" },
  { id:"v37", lv:1, es:"cómo", de:"wie", pos:"adv", ex:"¿Cómo estás?", exde:"Wie geht’s dir?" },
  { id:"v38", lv:1, es:"cuánto", de:"wie viel", pos:"pron", ex:"¿Cuánto cuesta?", exde:"Wie viel kostet das?" },
  { id:"v39", lv:1, es:"cuál", de:"welche(r/s)", pos:"pron", ex:"¿Cuál prefieres?", exde:"Welchen bevorzugst du?" },
  { id:"v40", lv:1, es:"ser", de:"sein (Wesen / Identität)", pos:"v", ex:"Soy profesor.", exde:"Ich bin Lehrer." },
  { id:"v41", lv:1, es:"estar", de:"sein (Zustand / Ort)", pos:"v", ex:"Estoy cansado.", exde:"Ich bin müde." },
  { id:"v42", lv:1, es:"tener", de:"haben", pos:"v", ex:"Tengo dos hermanos.", exde:"Ich habe zwei Geschwister." },
  { id:"v43", lv:1, es:"ir", de:"gehen / fahren", pos:"v", ex:"Voy a casa.", exde:"Ich gehe nach Hause." },
  { id:"v44", lv:1, es:"hacer", de:"machen / tun", pos:"v", ex:"¿Qué haces?", exde:"Was machst du?" },
  { id:"v45", lv:1, es:"poder", de:"können", pos:"v", ex:"¿Puedes ayudarme?", exde:"Kannst du mir helfen?" },
  { id:"v46", lv:1, es:"querer", de:"wollen / lieben", pos:"v", ex:"Quiero agua.", exde:"Ich möchte Wasser." },
  { id:"v47", lv:1, es:"decir", de:"sagen", pos:"v", ex:"¿Qué dices?", exde:"Was sagst du?" },
  { id:"v48", lv:1, es:"ver", de:"sehen", pos:"v", ex:"Veo una película.", exde:"Ich sehe einen Film." },
  { id:"v49", lv:1, es:"dar", de:"geben", pos:"v", ex:"Dame un minuto.", exde:"Gib mir eine Minute." },
  { id:"v50", lv:1, es:"saber", de:"wissen / können (Fähigkeit)", pos:"v", ex:"No sé.", exde:"Ich weiß nicht." },
  { id:"v51", lv:1, es:"hablar", de:"sprechen", pos:"v", ex:"Hablo un poco de español.", exde:"Ich spreche ein bisschen Spanisch." },
  { id:"v52", lv:1, es:"comer", de:"essen", pos:"v", ex:"Como a las dos.", exde:"Ich esse um zwei." },
  { id:"v53", lv:1, es:"beber", de:"trinken", pos:"v", ex:"Bebo agua.", exde:"Ich trinke Wasser." },
  { id:"v54", lv:1, es:"vivir", de:"leben / wohnen", pos:"v", ex:"Vivo en Berlín.", exde:"Ich wohne in Berlin." },
  { id:"v55", lv:1, es:"llegar", de:"ankommen", pos:"v", ex:"Llego mañana.", exde:"Ich komme morgen an." },
  { id:"v56", lv:1, es:"venir", de:"kommen", pos:"v", ex:"¿Vienes conmigo?", exde:"Kommst du mit mir?" },
  { id:"v57", lv:1, es:"llamarse", de:"heißen", pos:"v", ex:"Me llamo Marta.", exde:"Ich heiße Marta." },
  { id:"v58", lv:1, es:"el agua", de:"das Wasser", pos:"n", ex:"Quiero agua, por favor.", exde:"Ich möchte Wasser, bitte." },
  { id:"v59", lv:1, es:"el pan", de:"das Brot", pos:"n", ex:"El pan está rico.", exde:"Das Brot ist lecker." },
  { id:"v60", lv:1, es:"el café", de:"der Kaffee", pos:"n", ex:"Un café con leche.", exde:"Einen Milchkaffee." },
  { id:"v61", lv:1, es:"la casa", de:"das Haus", pos:"n", ex:"Esta es mi casa.", exde:"Das ist mein Haus." },
  { id:"v62", lv:1, es:"el día", de:"der Tag", pos:"n", ex:"Hoy es un buen día.", exde:"Heute ist ein guter Tag." },
  { id:"v63", lv:1, es:"la noche", de:"die Nacht", pos:"n", ex:"Buenas noches.", exde:"Gute Nacht." },
  { id:"v64", lv:1, es:"el tiempo", de:"die Zeit / das Wetter", pos:"n", ex:"No tengo tiempo.", exde:"Ich habe keine Zeit." },
  { id:"v65", lv:1, es:"la gente", de:"die Leute", pos:"n", ex:"Hay mucha gente.", exde:"Es sind viele Leute da." },
  { id:"v66", lv:1, es:"el amigo", de:"der Freund", pos:"n", ex:"Es mi mejor amigo.", exde:"Er ist mein bester Freund." },
  { id:"v67", lv:1, es:"la familia", de:"die Familie", pos:"n", ex:"Mi familia es grande.", exde:"Meine Familie ist groß." },
  { id:"v68", lv:1, es:"el hombre", de:"der Mann", pos:"n", ex:"El hombre habla inglés.", exde:"Der Mann spricht Englisch." },
  { id:"v69", lv:1, es:"la mujer", de:"die Frau", pos:"n", ex:"La mujer es médica.", exde:"Die Frau ist Ärztin." },
  { id:"v70", lv:1, es:"el niño", de:"das Kind / der Junge", pos:"n", ex:"El niño tiene cinco años.", exde:"Das Kind ist fünf Jahre alt." },
  { id:"v71", lv:1, es:"la ciudad", de:"die Stadt", pos:"n", ex:"Me gusta la ciudad.", exde:"Ich mag die Stadt." },
  { id:"v72", lv:1, es:"el país", de:"das Land", pos:"n", ex:"España es un país bonito.", exde:"Spanien ist ein schönes Land." },
  { id:"v73", lv:1, es:"el año", de:"das Jahr", pos:"n", ex:"Este año viajo a España.", exde:"Dieses Jahr reise ich nach Spanien." },
  { id:"v74", lv:1, es:"la cosa", de:"die Sache / das Ding", pos:"n", ex:"Es una cosa importante.", exde:"Das ist eine wichtige Sache." },
  { id:"v75", lv:1, es:"la vida", de:"das Leben", pos:"n", ex:"La vida es corta.", exde:"Das Leben ist kurz." },
  { id:"v76", lv:1, es:"el trabajo", de:"die Arbeit", pos:"n", ex:"Voy al trabajo.", exde:"Ich gehe zur Arbeit." },
  { id:"v77", lv:1, es:"bueno", de:"gut", pos:"adj", ex:"Es un buen libro.", exde:"Es ist ein gutes Buch." },
  { id:"v78", lv:1, es:"malo", de:"schlecht", pos:"adj", ex:"Hoy es un mal día.", exde:"Heute ist ein schlechter Tag." },
  { id:"v79", lv:1, es:"grande", de:"groß", pos:"adj", ex:"Una casa grande.", exde:"Ein großes Haus." },
  { id:"v80", lv:1, es:"pequeño", de:"klein", pos:"adj", ex:"Un pueblo pequeño.", exde:"Ein kleines Dorf." },
  { id:"v81", lv:1, es:"mucho", de:"viel", pos:"adj", ex:"Tengo mucho trabajo.", exde:"Ich habe viel Arbeit." },
  { id:"v82", lv:1, es:"poco", de:"wenig", pos:"adj", ex:"Hablo poco español.", exde:"Ich spreche wenig Spanisch." },
  { id:"v83", lv:1, es:"más", de:"mehr", pos:"adv", ex:"Quiero más agua.", exde:"Ich möchte mehr Wasser." },
  { id:"v84", lv:1, es:"muy", de:"sehr", pos:"adv", ex:"Estoy muy bien.", exde:"Mir geht es sehr gut." },
  { id:"v85", lv:1, es:"bien", de:"gut (Adverb)", pos:"adv", ex:"Todo está bien.", exde:"Alles ist gut." },
  { id:"v86", lv:1, es:"ahora", de:"jetzt", pos:"adv", ex:"Ahora no puedo.", exde:"Jetzt kann ich nicht." },
  { id:"v87", lv:1, es:"hoy", de:"heute", pos:"adv", ex:"Hoy estudio español.", exde:"Heute lerne ich Spanisch." },
  { id:"v88", lv:1, es:"mañana", de:"morgen / der Morgen", pos:"adv", ex:"Hasta mañana.", exde:"Bis morgen." },
  { id:"v89", lv:1, es:"siempre", de:"immer", pos:"adv", ex:"Siempre llego tarde.", exde:"Ich komme immer zu spät." },
  { id:"v90", lv:1, es:"también", de:"auch", pos:"adv", ex:"Yo también quiero café.", exde:"Ich möchte auch Kaffee." },
  { id:"v91", lv:1, es:"pero", de:"aber", pos:"conj", ex:"Quiero ir, pero no puedo.", exde:"Ich will gehen, aber ich kann nicht." },
  { id:"v92", lv:1, es:"porque", de:"weil", pos:"conj", ex:"Estudio porque me gusta.", exde:"Ich lerne, weil es mir Spaß macht." },
  { id:"v93", lv:1, es:"con", de:"mit", pos:"prep", ex:"Voy con mis amigos.", exde:"Ich gehe mit meinen Freunden." },
  { id:"v94", lv:1, es:"sin", de:"ohne", pos:"prep", ex:"Café sin leche.", exde:"Kaffee ohne Milch." },
  { id:"v95", lv:1, es:"para", de:"für / um zu", pos:"prep", ex:"Esto es para ti.", exde:"Das ist für dich." },
  { id:"v96", lv:1, es:"por", de:"wegen / durch / pro", pos:"prep", ex:"Gracias por todo.", exde:"Danke für alles." },
  { id:"v97", lv:1, es:"en", de:"in / an / auf", pos:"prep", ex:"Estoy en casa.", exde:"Ich bin zu Hause." },
  { id:"v98", lv:1, es:"de", de:"von / aus", pos:"prep", ex:"Soy de Alemania.", exde:"Ich komme aus Deutschland." },
  { id:"v99", lv:1, es:"a", de:"nach / zu", pos:"prep", ex:"Voy a España.", exde:"Ich fahre nach Spanien." },
  { id:"v100", lv:1, es:"y", de:"und", pos:"conj", ex:"Tú y yo.", exde:"Du und ich." },

  { id:"v101", lv:2, es:"uno", de:"eins", pos:"num", ex:"Quiero uno.", exde:"Ich möchte eins." },
  { id:"v102", lv:2, es:"dos", de:"zwei", pos:"num", ex:"Tengo dos gatos.", exde:"Ich habe zwei Katzen." },
  { id:"v103", lv:2, es:"tres", de:"drei", pos:"num", ex:"Son las tres.", exde:"Es ist drei Uhr." },
  { id:"v104", lv:2, es:"cuatro", de:"vier", pos:"num", ex:"Cuatro personas.", exde:"Vier Personen." },
  { id:"v105", lv:2, es:"cinco", de:"fünf", pos:"num", ex:"Cinco minutos.", exde:"Fünf Minuten." },
  { id:"v106", lv:2, es:"seis", de:"sechs", pos:"num", ex:"Son las seis.", exde:"Es ist sechs Uhr." },
  { id:"v107", lv:2, es:"siete", de:"sieben", pos:"num", ex:"Siete días.", exde:"Sieben Tage." },
  { id:"v108", lv:2, es:"ocho", de:"acht", pos:"num", ex:"A las ocho.", exde:"Um acht Uhr." },
  { id:"v109", lv:2, es:"nueve", de:"neun", pos:"num", ex:"Nueve euros.", exde:"Neun Euro." },
  { id:"v110", lv:2, es:"diez", de:"zehn", pos:"num", ex:"Diez años.", exde:"Zehn Jahre." },
  { id:"v111", lv:2, es:"veinte", de:"zwanzig", pos:"num", ex:"Veinte euros.", exde:"Zwanzig Euro." },
  { id:"v112", lv:2, es:"cien", de:"hundert", pos:"num", ex:"Cien palabras.", exde:"Hundert Wörter." },
  { id:"v113", lv:2, es:"lunes", de:"Montag", pos:"n", ex:"El lunes trabajo.", exde:"Am Montag arbeite ich." },
  { id:"v114", lv:2, es:"martes", de:"Dienstag", pos:"n", ex:"Nos vemos el martes.", exde:"Wir sehen uns am Dienstag." },
  { id:"v115", lv:2, es:"miércoles", de:"Mittwoch", pos:"n", ex:"El miércoles estudio.", exde:"Am Mittwoch lerne ich." },
  { id:"v116", lv:2, es:"jueves", de:"Donnerstag", pos:"n", ex:"El jueves hay mercado.", exde:"Donnerstags ist Markt." },
  { id:"v117", lv:2, es:"viernes", de:"Freitag", pos:"n", ex:"El viernes salgo.", exde:"Am Freitag gehe ich aus." },
  { id:"v118", lv:2, es:"sábado", de:"Samstag", pos:"n", ex:"El sábado descanso.", exde:"Am Samstag ruhe ich mich aus." },
  { id:"v119", lv:2, es:"domingo", de:"Sonntag", pos:"n", ex:"El domingo veo a mi familia.", exde:"Am Sonntag sehe ich meine Familie." },
  { id:"v120", lv:2, es:"la semana", de:"die Woche", pos:"n", ex:"Esta semana estoy ocupado.", exde:"Diese Woche bin ich beschäftigt." },
  { id:"v121", lv:2, es:"el mes", de:"der Monat", pos:"n", ex:"El mes que viene viajo.", exde:"Nächsten Monat reise ich." },
  { id:"v122", lv:2, es:"enero", de:"Januar", pos:"n", ex:"En enero hace frío.", exde:"Im Januar ist es kalt." },
  { id:"v123", lv:2, es:"la comida", de:"das Essen / das Mittagessen", pos:"n", ex:"La comida está lista.", exde:"Das Essen ist fertig." },
  { id:"v124", lv:2, es:"el desayuno", de:"das Frühstück", pos:"n", ex:"El desayuno es a las ocho.", exde:"Das Frühstück ist um acht." },
  { id:"v125", lv:2, es:"la manzana", de:"der Apfel", pos:"n", ex:"Una manzana al día.", exde:"Ein Apfel am Tag." },
  { id:"v126", lv:2, es:"el pollo", de:"das Hähnchen", pos:"n", ex:"Quiero pollo con arroz.", exde:"Ich möchte Hähnchen mit Reis." },
  { id:"v127", lv:2, es:"el pescado", de:"der Fisch", pos:"n", ex:"El pescado está fresco.", exde:"Der Fisch ist frisch." },
  { id:"v128", lv:2, es:"la carne", de:"das Fleisch", pos:"n", ex:"No como carne.", exde:"Ich esse kein Fleisch." },
  { id:"v129", lv:2, es:"el arroz", de:"der Reis", pos:"n", ex:"Arroz con verduras.", exde:"Reis mit Gemüse." },
  { id:"v130", lv:2, es:"la ensalada", de:"der Salat", pos:"n", ex:"Una ensalada mixta.", exde:"Ein gemischter Salat." },
  { id:"v131", lv:2, es:"el queso", de:"der Käse", pos:"n", ex:"Queso y pan.", exde:"Käse und Brot." },
  { id:"v132", lv:2, es:"la leche", de:"die Milch", pos:"n", ex:"Café con leche.", exde:"Kaffee mit Milch." },
  { id:"v133", lv:2, es:"el vino", de:"der Wein", pos:"n", ex:"Una copa de vino.", exde:"Ein Glas Wein." },
  { id:"v134", lv:2, es:"la cerveza", de:"das Bier", pos:"n", ex:"Una cerveza, por favor.", exde:"Ein Bier, bitte." },
  { id:"v135", lv:2, es:"el restaurante", de:"das Restaurant", pos:"n", ex:"Vamos al restaurante.", exde:"Wir gehen ins Restaurant." },
  { id:"v136", lv:2, es:"la cuenta", de:"die Rechnung", pos:"n", ex:"La cuenta, por favor.", exde:"Die Rechnung, bitte." },
  { id:"v137", lv:2, es:"el hotel", de:"das Hotel", pos:"n", ex:"Dormimos en un hotel.", exde:"Wir schlafen in einem Hotel." },
  { id:"v138", lv:2, es:"el tren", de:"der Zug", pos:"n", ex:"El tren llega tarde.", exde:"Der Zug kommt zu spät." },
  { id:"v139", lv:2, es:"el autobús", de:"der Bus", pos:"n", ex:"Cojo el autobús.", exde:"Ich nehme den Bus." },
  { id:"v140", lv:2, es:"el avión", de:"das Flugzeug", pos:"n", ex:"El avión sale a las diez.", exde:"Das Flugzeug startet um zehn." },
  { id:"v141", lv:2, es:"el coche", de:"das Auto", pos:"n", ex:"Voy en coche.", exde:"Ich fahre mit dem Auto." },
  { id:"v142", lv:2, es:"la estación", de:"der Bahnhof", pos:"n", ex:"La estación está cerca.", exde:"Der Bahnhof ist in der Nähe." },
  { id:"v143", lv:2, es:"el aeropuerto", de:"der Flughafen", pos:"n", ex:"Vamos al aeropuerto.", exde:"Wir fahren zum Flughafen." },
  { id:"v144", lv:2, es:"la calle", de:"die Straße", pos:"n", ex:"Vivo en esta calle.", exde:"Ich wohne in dieser Straße." },
  { id:"v145", lv:2, es:"la plaza", de:"der Platz", pos:"n", ex:"Quedamos en la plaza.", exde:"Wir treffen uns auf dem Platz." },
  { id:"v146", lv:2, es:"el mercado", de:"der Markt", pos:"n", ex:"Compro fruta en el mercado.", exde:"Ich kaufe Obst auf dem Markt." },
  { id:"v147", lv:2, es:"la tienda", de:"das Geschäft", pos:"n", ex:"La tienda abre a las nueve.", exde:"Das Geschäft öffnet um neun." },
  { id:"v148", lv:2, es:"el dinero", de:"das Geld", pos:"n", ex:"No tengo dinero.", exde:"Ich habe kein Geld." },
  { id:"v149", lv:2, es:"el precio", de:"der Preis", pos:"n", ex:"El precio es bueno.", exde:"Der Preis ist gut." },
  { id:"v150", lv:2, es:"barato", de:"günstig", pos:"adj", ex:"Es muy barato.", exde:"Es ist sehr günstig." },
  { id:"v151", lv:2, es:"caro", de:"teuer", pos:"adj", ex:"Este hotel es caro.", exde:"Dieses Hotel ist teuer." },
  { id:"v152", lv:2, es:"abierto", de:"offen", pos:"adj", ex:"El museo está abierto.", exde:"Das Museum ist offen." },
  { id:"v153", lv:2, es:"cerrado", de:"geschlossen", pos:"adj", ex:"Hoy está cerrado.", exde:"Heute ist geschlossen." },
  { id:"v154", lv:2, es:"la puerta", de:"die Tür", pos:"n", ex:"Cierra la puerta.", exde:"Mach die Tür zu." },
  { id:"v155", lv:2, es:"la ventana", de:"das Fenster", pos:"n", ex:"Abre la ventana.", exde:"Mach das Fenster auf." },
  { id:"v156", lv:2, es:"la mesa", de:"der Tisch", pos:"n", ex:"La mesa está ocupada.", exde:"Der Tisch ist besetzt." },
  { id:"v157", lv:2, es:"la silla", de:"der Stuhl", pos:"n", ex:"Siéntate en la silla.", exde:"Setz dich auf den Stuhl." },
  { id:"v158", lv:2, es:"la cama", de:"das Bett", pos:"n", ex:"Voy a la cama.", exde:"Ich gehe ins Bett." },
  { id:"v159", lv:2, es:"el baño", de:"das Badezimmer / die Toilette", pos:"n", ex:"¿Dónde está el baño?", exde:"Wo ist die Toilette?" },
  { id:"v160", lv:2, es:"la cocina", de:"die Küche", pos:"n", ex:"Estoy en la cocina.", exde:"Ich bin in der Küche." },
  { id:"v161", lv:2, es:"la habitación", de:"das Zimmer", pos:"n", ex:"Una habitación doble.", exde:"Ein Doppelzimmer." },
  { id:"v162", lv:2, es:"el teléfono", de:"das Telefon", pos:"n", ex:"¿Tienes teléfono?", exde:"Hast du ein Telefon?" },
  { id:"v163", lv:2, es:"la pregunta", de:"die Frage", pos:"n", ex:"Tengo una pregunta.", exde:"Ich habe eine Frage." },
  { id:"v164", lv:2, es:"la respuesta", de:"die Antwort", pos:"n", ex:"No sé la respuesta.", exde:"Ich kenne die Antwort nicht." },
  { id:"v165", lv:2, es:"la mano", de:"die Hand", pos:"n", ex:"Dame la mano.", exde:"Gib mir die Hand." },
  { id:"v166", lv:2, es:"el ojo", de:"das Auge", pos:"n", ex:"Tienes los ojos verdes.", exde:"Du hast grüne Augen." },
  { id:"v167", lv:2, es:"la cabeza", de:"der Kopf", pos:"n", ex:"Me duele la cabeza.", exde:"Mir tut der Kopf weh." },
  { id:"v168", lv:2, es:"rojo", de:"rot", pos:"adj", ex:"Un coche rojo.", exde:"Ein rotes Auto." },
  { id:"v169", lv:2, es:"azul", de:"blau", pos:"adj", ex:"El cielo está azul.", exde:"Der Himmel ist blau." },
  { id:"v170", lv:2, es:"verde", de:"grün", pos:"adj", ex:"Me gusta el verde.", exde:"Ich mag Grün." },
  { id:"v171", lv:2, es:"negro", de:"schwarz", pos:"adj", ex:"Un gato negro.", exde:"Eine schwarze Katze." },
  { id:"v172", lv:2, es:"blanco", de:"weiß", pos:"adj", ex:"Una camisa blanca.", exde:"Ein weißes Hemd." },
  { id:"v173", lv:2, es:"amarillo", de:"gelb", pos:"adj", ex:"El sol es amarillo.", exde:"Die Sonne ist gelb." },
  { id:"v174", lv:2, es:"comprar", de:"kaufen", pos:"v", ex:"Compro pan.", exde:"Ich kaufe Brot." },
  { id:"v175", lv:2, es:"vender", de:"verkaufen", pos:"v", ex:"Venden fruta aquí.", exde:"Hier verkaufen sie Obst." },
  { id:"v176", lv:2, es:"pagar", de:"bezahlen", pos:"v", ex:"¿Puedo pagar con tarjeta?", exde:"Kann ich mit Karte zahlen?" },
  { id:"v177", lv:2, es:"pedir", de:"bestellen / bitten", pos:"v", ex:"Pido la cuenta.", exde:"Ich bestelle die Rechnung." },
  { id:"v178", lv:2, es:"buscar", de:"suchen", pos:"v", ex:"Busco un hotel.", exde:"Ich suche ein Hotel." },
  { id:"v179", lv:2, es:"encontrar", de:"finden", pos:"v", ex:"No encuentro las llaves.", exde:"Ich finde die Schlüssel nicht." },
  { id:"v180", lv:2, es:"esperar", de:"warten / hoffen", pos:"v", ex:"Espero el autobús.", exde:"Ich warte auf den Bus." },
  { id:"v181", lv:2, es:"necesitar", de:"brauchen", pos:"v", ex:"Necesito ayuda.", exde:"Ich brauche Hilfe." },
  { id:"v182", lv:2, es:"trabajar", de:"arbeiten", pos:"v", ex:"Trabajo en una oficina.", exde:"Ich arbeite in einem Büro." },
  { id:"v183", lv:2, es:"estudiar", de:"lernen / studieren", pos:"v", ex:"Estudio español cada día.", exde:"Ich lerne jeden Tag Spanisch." },
  { id:"v184", lv:2, es:"aprender", de:"lernen (etwas Neues)", pos:"v", ex:"Aprendo vocabulario.", exde:"Ich lerne Vokabeln." },
  { id:"v185", lv:2, es:"entender", de:"verstehen", pos:"v", ex:"No entiendo.", exde:"Ich verstehe nicht." },
  { id:"v186", lv:2, es:"pensar", de:"denken", pos:"v", ex:"Pienso en ti.", exde:"Ich denke an dich." },
  { id:"v187", lv:2, es:"salir", de:"hinausgehen / ausgehen", pos:"v", ex:"Salgo con amigos.", exde:"Ich gehe mit Freunden aus." },
  { id:"v188", lv:2, es:"entrar", de:"hineingehen", pos:"v", ex:"Entra, por favor.", exde:"Komm rein, bitte." },
  { id:"v189", lv:2, es:"volver", de:"zurückkommen", pos:"v", ex:"Vuelvo a las seis.", exde:"Ich komme um sechs zurück." },
  { id:"v190", lv:2, es:"dormir", de:"schlafen", pos:"v", ex:"Duermo ocho horas.", exde:"Ich schlafe acht Stunden." },
  { id:"v191", lv:2, es:"ayudar", de:"helfen", pos:"v", ex:"¿Me puedes ayudar?", exde:"Kannst du mir helfen?" },
  { id:"v192", lv:2, es:"mirar", de:"schauen", pos:"v", ex:"Miro la tele.", exde:"Ich schaue fern." },
  { id:"v193", lv:2, es:"escuchar", de:"zuhören / hören", pos:"v", ex:"Escucho música.", exde:"Ich höre Musik." },
  { id:"v194", lv:2, es:"gustar", de:"gefallen / mögen", pos:"v", ex:"Me gusta el café.", exde:"Ich mag Kaffee." },
  { id:"v195", lv:2, es:"abrir", de:"öffnen", pos:"v", ex:"Abro la puerta.", exde:"Ich öffne die Tür." },
  { id:"v196", lv:2, es:"cerrar", de:"schließen", pos:"v", ex:"Cierra la ventana.", exde:"Schließ das Fenster." },
  { id:"v197", lv:2, es:"conocer", de:"kennen / kennenlernen", pos:"v", ex:"Conozco Madrid.", exde:"Ich kenne Madrid." },
  { id:"v198", lv:2, es:"llevar", de:"tragen / mitnehmen / dauern", pos:"v", ex:"Llevo una chaqueta.", exde:"Ich trage eine Jacke." },
  { id:"v199", lv:2, es:"pasar", de:"verbringen / passieren", pos:"v", ex:"¿Qué pasa?", exde:"Was ist los?" },
  { id:"v200", lv:2, es:"quedar", de:"bleiben / sich treffen", pos:"v", ex:"¿Quedamos a las cinco?", exde:"Treffen wir uns um fünf?" },

  { id:"v201", lv:3, es:"la mañana", de:"der Morgen / der Vormittag", pos:"n", ex:"Por la mañana corro.", exde:"Morgens jogge ich." },
  { id:"v202", lv:3, es:"la tarde", de:"der Nachmittag / der Abend", pos:"n", ex:"Por la tarde estudio.", exde:"Nachmittags lerne ich." },
  { id:"v203", lv:3, es:"ayer", de:"gestern", pos:"adv", ex:"Ayer fui al cine.", exde:"Gestern war ich im Kino." },
  { id:"v204", lv:3, es:"nunca", de:"nie", pos:"adv", ex:"Nunca como carne.", exde:"Ich esse nie Fleisch." },
  { id:"v205", lv:3, es:"ya", de:"schon / jetzt", pos:"adv", ex:"Ya está.", exde:"Es ist schon fertig." },
  { id:"v206", lv:3, es:"todavía", de:"noch", pos:"adv", ex:"Todavía no sé.", exde:"Ich weiß es noch nicht." },
  { id:"v207", lv:3, es:"aquí", de:"hier", pos:"adv", ex:"Ven aquí.", exde:"Komm her." },
  { id:"v208", lv:3, es:"allí", de:"dort", pos:"adv", ex:"El banco está allí.", exde:"Die Bank ist dort." },
  { id:"v209", lv:3, es:"cerca", de:"in der Nähe", pos:"adv", ex:"Vivo cerca.", exde:"Ich wohne in der Nähe." },
  { id:"v210", lv:3, es:"lejos", de:"weit weg", pos:"adv", ex:"Está lejos del centro.", exde:"Es ist weit vom Zentrum." },
  { id:"v211", lv:3, es:"antes", de:"vorher", pos:"adv", ex:"Antes de comer, lavo las manos.", exde:"Vor dem Essen wasche ich die Hände." },
  { id:"v212", lv:3, es:"después", de:"danach", pos:"adv", ex:"Después vamos a casa.", exde:"Danach gehen wir nach Hause." },
  { id:"v213", lv:3, es:"entonces", de:"dann / also", pos:"adv", ex:"Entonces, ¿qué hacemos?", exde:"Also, was machen wir?" },
  { id:"v214", lv:3, es:"aunque", de:"obwohl", pos:"conj", ex:"Salgo aunque llueve.", exde:"Ich gehe raus, obwohl es regnet." },
  { id:"v215", lv:3, es:"si", de:"wenn / falls", pos:"conj", ex:"Si tienes tiempo, llama.", exde:"Wenn du Zeit hast, ruf an." },
  { id:"v216", lv:3, es:"cuando", de:"wenn / als", pos:"conj", ex:"Cuando llego, te aviso.", exde:"Wenn ich ankomme, sage ich Bescheid." },
  { id:"v217", lv:3, es:"el hermano", de:"der Bruder", pos:"n", ex:"Mi hermano es mayor.", exde:"Mein Bruder ist älter." },
  { id:"v218", lv:3, es:"la hermana", de:"die Schwester", pos:"n", ex:"Mi hermana vive en Sevilla.", exde:"Meine Schwester wohnt in Sevilla." },
  { id:"v219", lv:3, es:"el padre", de:"der Vater", pos:"n", ex:"Mi padre cocina bien.", exde:"Mein Vater kocht gut." },
  { id:"v220", lv:3, es:"la madre", de:"die Mutter", pos:"n", ex:"Mi madre es profesora.", exde:"Meine Mutter ist Lehrerin." },
  { id:"v221", lv:3, es:"el hijo", de:"der Sohn", pos:"n", ex:"Tienen un hijo.", exde:"Sie haben einen Sohn." },
  { id:"v222", lv:3, es:"la hija", de:"die Tochter", pos:"n", ex:"Su hija tiene diez años.", exde:"Ihre Tochter ist zehn." },
  { id:"v223", lv:3, es:"el perro", de:"der Hund", pos:"n", ex:"El perro es muy bueno.", exde:"Der Hund ist sehr lieb." },
  { id:"v224", lv:3, es:"el gato", de:"die Katze", pos:"n", ex:"El gato duerme mucho.", exde:"Die Katze schläft viel." },
  { id:"v225", lv:3, es:"el libro", de:"das Buch", pos:"n", ex:"Leo un libro.", exde:"Ich lese ein Buch." },
  { id:"v226", lv:3, es:"la película", de:"der Film", pos:"n", ex:"Vemos una película.", exde:"Wir schauen einen Film." },
  { id:"v227", lv:3, es:"la música", de:"die Musik", pos:"n", ex:"Me encanta la música.", exde:"Ich liebe Musik." },
  { id:"v228", lv:3, es:"el problema", de:"das Problem", pos:"n", ex:"No hay problema.", exde:"Kein Problem." },
  { id:"v229", lv:3, es:"la idea", de:"die Idee", pos:"n", ex:"Es una buena idea.", exde:"Das ist eine gute Idee." },
  { id:"v230", lv:3, es:"la hora", de:"die Stunde / Uhrzeit", pos:"n", ex:"¿Qué hora es?", exde:"Wie spät ist es?" },
  { id:"v231", lv:3, es:"el minuto", de:"die Minute", pos:"n", ex:"Un minuto, por favor.", exde:"Eine Minute, bitte." },
  { id:"v232", lv:3, es:"el médico", de:"der Arzt", pos:"n", ex:"Voy al médico.", exde:"Ich gehe zum Arzt." },
  { id:"v233", lv:3, es:"el hospital", de:"das Krankenhaus", pos:"n", ex:"Trabaja en el hospital.", exde:"Er arbeitet im Krankenhaus." },
  { id:"v234", lv:3, es:"la escuela", de:"die Schule", pos:"n", ex:"Los niños van a la escuela.", exde:"Die Kinder gehen zur Schule." },
  { id:"v235", lv:3, es:"el colegio", de:"die Schule (oft Grund-/weiterführend)", pos:"n", ex:"El colegio empieza a las nueve.", exde:"Die Schule beginnt um neun." },
  { id:"v236", lv:3, es:"la universidad", de:"die Universität", pos:"n", ex:"Estudio en la universidad.", exde:"Ich studiere an der Uni." },
  { id:"v237", lv:3, es:"la oficina", de:"das Büro", pos:"n", ex:"Trabajo en una oficina.", exde:"Ich arbeite in einem Büro." },
  { id:"v238", lv:3, es:"el jefe", de:"der Chef", pos:"n", ex:"Mi jefe es amable.", exde:"Mein Chef ist freundlich." },
  { id:"v239", lv:3, es:"el examen", de:"die Prüfung", pos:"n", ex:"El examen es mañana.", exde:"Die Prüfung ist morgen." },
  { id:"v240", lv:3, es:"feliz", de:"glücklich", pos:"adj", ex:"Estoy muy feliz.", exde:"Ich bin sehr glücklich." },
  { id:"v241", lv:3, es:"triste", de:"traurig", pos:"adj", ex:"Está triste hoy.", exde:"Er ist heute traurig." },
  { id:"v242", lv:3, es:"cansado", de:"müde", pos:"adj", ex:"Estoy cansado.", exde:"Ich bin müde." },
  { id:"v243", lv:3, es:"ocupado", de:"beschäftigt", pos:"adj", ex:"Estoy ocupado ahora.", exde:"Ich bin gerade beschäftigt." },
  { id:"v244", lv:3, es:"fácil", de:"einfach", pos:"adj", ex:"No es fácil.", exde:"Es ist nicht einfach." },
  { id:"v245", lv:3, es:"difícil", de:"schwierig", pos:"adj", ex:"El examen es difícil.", exde:"Die Prüfung ist schwer." },
  { id:"v246", lv:3, es:"importante", de:"wichtig", pos:"adj", ex:"Es importante estudiar.", exde:"Es ist wichtig zu lernen." },
  { id:"v247", lv:3, es:"bonito", de:"schön", pos:"adj", ex:"Qué ciudad tan bonita.", exde:"Was für eine schöne Stadt." },
  { id:"v248", lv:3, es:"nuevo", de:"neu", pos:"adj", ex:"Tengo un teléfono nuevo.", exde:"Ich habe ein neues Handy." },
  { id:"v249", lv:3, es:"viejo", de:"alt", pos:"adj", ex:"Es un barrio viejo.", exde:"Es ist ein altes Viertel." },
  { id:"v250", lv:3, es:"joven", de:"jung", pos:"adj", ex:"Es muy joven.", exde:"Er/sie ist sehr jung." },
  { id:"v251", lv:3, es:"caliente", de:"heiß / warm", pos:"adj", ex:"El café está caliente.", exde:"Der Kaffee ist heiß." },
  { id:"v252", lv:3, es:"frío", de:"kalt", pos:"adj", ex:"Hace frío.", exde:"Es ist kalt." },
  { id:"v253", lv:3, es:"lleno", de:"voll", pos:"adj", ex:"El tren está lleno.", exde:"Der Zug ist voll." },
  { id:"v254", lv:3, es:"vacío", de:"leer", pos:"adj", ex:"La calle está vacía.", exde:"Die Straße ist leer." },
  { id:"v255", lv:3, es:"mismo", de:"gleich / selbst", pos:"adj", ex:"El mismo día.", exde:"Am selben Tag." },
  { id:"v256", lv:3, es:"otro", de:"anderer", pos:"adj", ex:"Otra vez, por favor.", exde:"Noch einmal, bitte." },
  { id:"v257", lv:3, es:"todo", de:"alles / ganz", pos:"pron", ex:"Todo está bien.", exde:"Alles ist gut." },
  { id:"v258", lv:3, es:"nada", de:"nichts", pos:"pron", ex:"No pasa nada.", exde:"Es ist nichts passiert. / Kein Problem." },
  { id:"v259", lv:3, es:"algo", de:"etwas", pos:"pron", ex:"Quiero algo de beber.", exde:"Ich möchte etwas zu trinken." },
  { id:"v260", lv:3, es:"alguien", de:"jemand", pos:"pron", ex:"¿Hay alguien en casa?", exde:"Ist jemand zu Hause?" },
  { id:"v261", lv:3, es:"nadie", de:"niemand", pos:"pron", ex:"No hay nadie.", exde:"Da ist niemand." },
  { id:"v262", lv:3, es:"leer", de:"lesen", pos:"v", ex:"Leo cada noche.", exde:"Ich lese jede Nacht." },
  { id:"v263", lv:3, es:"escribir", de:"schreiben", pos:"v", ex:"Escribo un mensaje.", exde:"Ich schreibe eine Nachricht." },
  { id:"v264", lv:3, es:"poner", de:"stellen / legen / machen", pos:"v", ex:"Pongo la mesa.", exde:"Ich decke den Tisch." },
  { id:"v265", lv:3, es:"traer", de:"bringen", pos:"v", ex:"¿Traes pan?", exde:"Bringst du Brot mit?" },
  { id:"v266", lv:3, es:"seguir", de:"folgen / weitermachen", pos:"v", ex:"Sigo estudiando.", exde:"Ich lerne weiter." },
  { id:"v267", lv:3, es:"empezar", de:"anfangen", pos:"v", ex:"Empezamos a las nueve.", exde:"Wir fangen um neun an." },
  { id:"v268", lv:3, es:"terminar", de:"beenden / fertig sein", pos:"v", ex:"Termino a las seis.", exde:"Ich bin um sechs fertig." },
  { id:"v269", lv:3, es:"dejar", de:"lassen / aufhören / hinterlassen", pos:"v", ex:"Dejo las llaves aquí.", exde:"Ich lasse die Schlüssel hier." },
  { id:"v270", lv:3, es:"perder", de:"verlieren / verpassen", pos:"v", ex:"No pierdas el tren.", exde:"Verpass den Zug nicht." },
  { id:"v271", lv:3, es:"ganar", de:"gewinnen / verdienen", pos:"v", ex:"Gano poco dinero.", exde:"Ich verdiene wenig Geld." },
  { id:"v272", lv:3, es:"cambiar", de:"ändern / wechseln", pos:"v", ex:"Quiero cambiar de hotel.", exde:"Ich möchte das Hotel wechseln." },
  { id:"v273", lv:3, es:"usar", de:"benutzen", pos:"v", ex:"¿Puedo usar el baño?", exde:"Kann ich die Toilette benutzen?" },
  { id:"v274", lv:3, es:"llamar", de:"anrufen / rufen", pos:"v", ex:"Te llamo luego.", exde:"Ich rufe dich später an." },
  { id:"v275", lv:3, es:"recordar", de:"sich erinnern", pos:"v", ex:"No recuerdo su nombre.", exde:"Ich erinnere mich nicht an seinen Namen." },
  { id:"v276", lv:3, es:"olvidar", de:"vergessen", pos:"v", ex:"Olvido las palabras.", exde:"Ich vergesse die Wörter." },
  { id:"v277", lv:3, es:"creer", de:"glauben", pos:"v", ex:"Creo que sí.", exde:"Ich glaube schon." },
  { id:"v278", lv:3, es:"parecer", de:"scheinen / finden", pos:"v", ex:"Me parece bien.", exde:"Das finde ich gut." },
  { id:"v279", lv:3, es:"sentir", de:"fühlen / bedauern", pos:"v", ex:"Lo siento.", exde:"Es tut mir leid." },
  { id:"v280", lv:3, es:"doler", de:"schmerzen", pos:"v", ex:"Me duele la cabeza.", exde:"Mir tut der Kopf weh." },
  { id:"v281", lv:3, es:"llover", de:"regnen", pos:"v", ex:"Llueve mucho.", exde:"Es regnet stark." },
  { id:"v282", lv:3, es:"el sol", de:"die Sonne", pos:"n", ex:"El sol brilla.", exde:"Die Sonne scheint." },
  { id:"v283", lv:3, es:"la lluvia", de:"der Regen", pos:"n", ex:"No me gusta la lluvia.", exde:"Ich mag den Regen nicht." },
  { id:"v284", lv:3, es:"el mar", de:"das Meer", pos:"n", ex:"Vamos al mar.", exde:"Wir fahren ans Meer." },
  { id:"v285", lv:3, es:"la montaña", de:"der Berg", pos:"n", ex:"Me gustan las montañas.", exde:"Ich mag die Berge." },
  { id:"v286", lv:3, es:"el árbol", de:"der Baum", pos:"n", ex:"Hay un árbol grande.", exde:"Da steht ein großer Baum." },
  { id:"v287", lv:3, es:"la playa", de:"der Strand", pos:"n", ex:"Pasamos el día en la playa.", exde:"Wir verbringen den Tag am Strand." },
  { id:"v288", lv:3, es:"el pueblo", de:"das Dorf / der Ort", pos:"n", ex:"Es un pueblo pequeño.", exde:"Es ist ein kleines Dorf." },
  { id:"v289", lv:3, es:"el centro", de:"das Zentrum", pos:"n", ex:"Vivo en el centro.", exde:"Ich wohne im Zentrum." },
  { id:"v290", lv:3, es:"el barrio", de:"das Viertel", pos:"n", ex:"Es un barrio tranquilo.", exde:"Es ist ein ruhiges Viertel." },
  { id:"v291", lv:3, es:"la llave", de:"der Schlüssel", pos:"n", ex:"¿Tienes las llaves?", exde:"Hast du die Schlüssel?" },
  { id:"v292", lv:3, es:"el billete", de:"das Ticket / der Schein", pos:"n", ex:"Un billete de tren.", exde:"Ein Zugticket." },
  { id:"v293", lv:3, es:"el pasaporte", de:"der Reisepass", pos:"n", ex:"¿Dónde está mi pasaporte?", exde:"Wo ist mein Pass?" },
  { id:"v294", lv:3, es:"la maleta", de:"der Koffer", pos:"n", ex:"Hago la maleta.", exde:"Ich packe den Koffer." },
  { id:"v295", lv:3, es:"el viaje", de:"die Reise", pos:"n", ex:"Buen viaje.", exde:"Gute Reise." },
  { id:"v296", lv:3, es:"la foto", de:"das Foto", pos:"n", ex:"Hago una foto.", exde:"Ich mache ein Foto." },
  { id:"v297", lv:3, es:"el correo", de:"die Post / die E-Mail", pos:"n", ex:"Te mando un correo.", exde:"Ich schicke dir eine Mail." },
  { id:"v298", lv:3, es:"la página", de:"die Seite", pos:"n", ex:"Mira esta página.", exde:"Schau dir diese Seite an." },
  { id:"v299", lv:3, es:"el ordenador", de:"der Computer", pos:"n", ex:"Trabajo con el ordenador.", exde:"Ich arbeite am Computer." },
  { id:"v300", lv:3, es:"internet", de:"das Internet", pos:"n", ex:"¿Hay internet?", exde:"Gibt es Internet?" },
  { id:"v301", lv:3, es:"la ropa", de:"die Kleidung", pos:"n", ex:"Compro ropa.", exde:"Ich kaufe Kleidung." },
  { id:"v302", lv:3, es:"la camisa", de:"das Hemd", pos:"n", ex:"Una camisa blanca.", exde:"Ein weißes Hemd." },
  { id:"v303", lv:3, es:"los zapatos", de:"die Schuhe", pos:"n", ex:"Estos zapatos son cómodos.", exde:"Diese Schuhe sind bequem." },
  { id:"v304", lv:3, es:"el abrigo", de:"der Mantel", pos:"n", ex:"Llevo un abrigo.", exde:"Ich trage einen Mantel." },
  { id:"v305", lv:3, es:"el cuerpo", de:"der Körper", pos:"n", ex:"Me duele el cuerpo.", exde:"Mir tut der Körper weh." },
  { id:"v306", lv:3, es:"el brazo", de:"der Arm", pos:"n", ex:"Me duele el brazo.", exde:"Mir tut der Arm weh." },
  { id:"v307", lv:3, es:"la pierna", de:"das Bein", pos:"n", ex:"Tengo las piernas cansadas.", exde:"Meine Beine sind müde." },
  { id:"v308", lv:3, es:"la boca", de:"der Mund", pos:"n", ex:"Abre la boca.", exde:"Mach den Mund auf." },
  { id:"v309", lv:3, es:"el corazón", de:"das Herz", pos:"n", ex:"Te quiero con todo el corazón.", exde:"Ich liebe dich von ganzem Herzen." },
  { id:"v310", lv:3, es:"la salud", de:"die Gesundheit", pos:"n", ex:"¡Salud!", exde:"Gesundheit! / Prost!" },
  { id:"v311", lv:3, es:"la medicina", de:"die Medizin", pos:"n", ex:"Tomo una medicina.", exde:"Ich nehme eine Medizin." },
  { id:"v312", lv:3, es:"el dolor", de:"der Schmerz", pos:"n", ex:"Tengo dolor de estómago.", exde:"Ich habe Magenschmerzen." },
  { id:"v313", lv:3, es:"el banco", de:"die Bank", pos:"n", ex:"Voy al banco.", exde:"Ich gehe zur Bank." },
  { id:"v314", lv:3, es:"el supermercado", de:"der Supermarkt", pos:"n", ex:"Voy al supermercado.", exde:"Ich gehe in den Supermarkt." },
  { id:"v315", lv:3, es:"la fruta", de:"das Obst", pos:"n", ex:"Como fruta cada día.", exde:"Ich esse jeden Tag Obst." },
  { id:"v316", lv:3, es:"la verdura", de:"das Gemüse", pos:"n", ex:"Me gustan las verduras.", exde:"Ich mag Gemüse." },
  { id:"v317", lv:3, es:"el huevo", de:"das Ei", pos:"n", ex:"Huevos con pan.", exde:"Eier mit Brot." },
  { id:"v318", lv:3, es:"el azúcar", de:"der Zucker", pos:"n", ex:"Sin azúcar, por favor.", exde:"Ohne Zucker, bitte." },
  { id:"v319", lv:3, es:"la sal", de:"das Salz", pos:"n", ex:"Poca sal, por favor.", exde:"Wenig Salz, bitte." },
  { id:"v320", lv:3, es:"el aceite", de:"das Öl", pos:"n", ex:"Aceite de oliva.", exde:"Olivenöl." },
  { id:"v321", lv:3, es:"cocinar", de:"kochen", pos:"v", ex:"Me gusta cocinar.", exde:"Ich koche gern." },
  { id:"v322", lv:3, es:"probar", de:"probieren / versuchen", pos:"v", ex:"Prueba esto.", exde:"Probier das." },
  { id:"v323", lv:3, es:"preferir", de:"bevorzugen", pos:"v", ex:"Prefiero té.", exde:"Ich bevorzuge Tee." },
  { id:"v324", lv:3, es:"encantar", de:"sehr gefallen", pos:"v", ex:"Me encanta España.", exde:"Ich liebe Spanien." },
  { id:"v325", lv:3, es:"odiar", de:"hassen", pos:"v", ex:"Odio madrugar.", exde:"Ich hasse frühes Aufstehen." },
  { id:"v326", lv:3, es:"reír", de:"lachen", pos:"v", ex:"Reímos mucho.", exde:"Wir lachen viel." },
  { id:"v327", lv:3, es:"llorar", de:"weinen", pos:"v", ex:"El niño llora.", exde:"Das Kind weint." },
  { id:"v328", lv:3, es:"correr", de:"rennen / laufen", pos:"v", ex:"Corro por la mañana.", exde:"Ich laufe morgens." },
  { id:"v329", lv:3, es:"caminar", de:"zu Fuß gehen", pos:"v", ex:"Caminamos por la ciudad.", exde:"Wir gehen durch die Stadt." },
  { id:"v330", lv:3, es:"viajar", de:"reisen", pos:"v", ex:"Viajo a menudo.", exde:"Ich reise oft." },
  { id:"v331", lv:3, es:"visitar", de:"besuchen", pos:"v", ex:"Visitamos un museo.", exde:"Wir besuchen ein Museum." },
  { id:"v332", lv:3, es:"quedarse", de:"bleiben", pos:"v", ex:"Me quedo en casa.", exde:"Ich bleibe zu Hause." },
  { id:"v333", lv:3, es:"levantarse", de:"aufstehen", pos:"v", ex:"Me levanto a las siete.", exde:"Ich stehe um sieben auf." },
  { id:"v334", lv:3, es:"acostarse", de:"sich hinlegen / schlafen gehen", pos:"v", ex:"Me acuesto tarde.", exde:"Ich gehe spät ins Bett." },
  { id:"v335", lv:3, es:"ducharse", de:"duschen", pos:"v", ex:"Me ducho por la mañana.", exde:"Ich dusche morgens." },
  { id:"v336", lv:3, es:"vestirse", de:"sich anziehen", pos:"v", ex:"Me visto rápido.", exde:"Ich ziehe mich schnell an." },
  { id:"v337", lv:3, es:"despertarse", de:"aufwachen", pos:"v", ex:"Me despierto temprano.", exde:"Ich wache früh auf." },
  { id:"v338", lv:3, es:"temprano", de:"früh", pos:"adv", ex:"Llego temprano.", exde:"Ich komme früh an." },
  { id:"v339", lv:3, es:"tarde", de:"spät / der Nachmittag", pos:"adv", ex:"Es demasiado tarde.", exde:"Es ist zu spät." },
  { id:"v340", lv:3, es:"despacio", de:"langsam", pos:"adv", ex:"Habla más despacio, por favor.", exde:"Sprich bitte langsamer." },
  { id:"v341", lv:3, es:"rápido", de:"schnell", pos:"adj", ex:"El tren es rápido.", exde:"Der Zug ist schnell." },
  { id:"v342", lv:3, es:"solo", de:"allein / nur", pos:"adv", ex:"Solo quiero agua.", exde:"Ich möchte nur Wasser." },
  { id:"v343", lv:3, es:"juntos", de:"zusammen", pos:"adv", ex:"Vamos juntos.", exde:"Wir gehen zusammen." },
  { id:"v344", lv:3, es:"casi", de:"fast", pos:"adv", ex:"Casi nunca como carne.", exde:"Ich esse fast nie Fleisch." },
  { id:"v345", lv:3, es:"demasiado", de:"zu viel / zu sehr", pos:"adv", ex:"Es demasiado caro.", exde:"Es ist zu teuer." },
  { id:"v346", lv:3, es:"bastante", de:"ziemlich / genug", pos:"adv", ex:"Es bastante fácil.", exde:"Es ist ziemlich einfach." },
  { id:"v347", lv:3, es:"todavía no", de:"noch nicht", pos:"phr", ex:"Todavía no entiendo.", exde:"Ich verstehe es noch nicht." },
  { id:"v348", lv:3, es:"por supuesto", de:"natürlich", pos:"phr", ex:"Por supuesto que sí.", exde:"Natürlich." },
  { id:"v349", lv:3, es:"de acuerdo", de:"einverstanden", pos:"phr", ex:"Estoy de acuerdo.", exde:"Ich bin einverstanden." },
  { id:"v350", lv:3, es:"lo siento", de:"es tut mir leid", pos:"phr", ex:"Lo siento, llego tarde.", exde:"Tut mir leid, ich komme zu spät." },

  { id:"v351", lv:4, es:"o sea", de:"das heißt / also", pos:"phr", ex:"No puedo, o sea, no tengo tiempo.", exde:"Ich kann nicht, das heißt, ich habe keine Zeit." },
  { id:"v352", lv:4, es:"mientras", de:"während", pos:"conj", ex:"Cocino mientras escuchas música.", exde:"Ich koche, während du Musik hörst." },
  { id:"v353", lv:4, es:"sin embargo", de:"jedoch", pos:"phr", ex:"Es difícil, sin embargo lo intento.", exde:"Es ist schwer, trotzdem versuche ich es." },
  { id:"v354", lv:4, es:"por eso", de:"deshalb", pos:"phr", ex:"Estoy cansado, por eso me quedo.", exde:"Ich bin müde, deshalb bleibe ich." },
  { id:"v355", lv:4, es:"además", de:"außerdem", pos:"adv", ex:"Además, es barato.", exde:"Außerdem ist es günstig." },
  { id:"v356", lv:4, es:"sobre", de:"über / auf", pos:"prep", ex:"Un libro sobre España.", exde:"Ein Buch über Spanien." },
  { id:"v357", lv:4, es:"entre", de:"zwischen", pos:"prep", ex:"Entre tú y yo.", exde:"Zwischen dir und mir." },
  { id:"v358", lv:4, es:"hasta", de:"bis", pos:"prep", ex:"Hasta luego.", exde:"Bis später." },
  { id:"v359", lv:4, es:"desde", de:"seit / von", pos:"prep", ex:"Vivo aquí desde 2020.", exde:"Ich wohne seit 2020 hier." },
  { id:"v360", lv:4, es:"contra", de:"gegen", pos:"prep", ex:"No estoy contra ti.", exde:"Ich bin nicht gegen dich." },
  { id:"v361", lv:4, es:"según", de:"laut / je nach", pos:"prep", ex:"Según el mapa, está cerca.", exde:"Laut Karte ist es nah." },
  { id:"v362", lv:4, es:"durante", de:"während", pos:"prep", ex:"Durante el viaje llovió.", exde:"Während der Reise hat es geregnet." },
  { id:"v363", lv:4, es:"hacia", de:"in Richtung", pos:"prep", ex:"Caminamos hacia el mar.", exde:"Wir laufen Richtung Meer." },
  { id:"v364", lv:4, es:"el gobierno", de:"die Regierung", pos:"n", ex:"El gobierno decide.", exde:"Die Regierung entscheidet." },
  { id:"v365", lv:4, es:"la ley", de:"das Gesetz", pos:"n", ex:"Es la ley.", exde:"Das ist das Gesetz." },
  { id:"v366", lv:4, es:"la noticia", de:"die Nachricht", pos:"n", ex:"Vi las noticias.", exde:"Ich habe die Nachrichten gesehen." },
  { id:"v367", lv:4, es:"el mundo", de:"die Welt", pos:"n", ex:"Viajo por el mundo.", exde:"Ich reise durch die Welt." },
  { id:"v368", lv:4, es:"la tierra", de:"die Erde / das Land", pos:"n", ex:"Cuidamos la tierra.", exde:"Wir kümmern uns um die Erde." },
  { id:"v369", lv:4, es:"el futuro", de:"die Zukunft", pos:"n", ex:"El futuro es incierto.", exde:"Die Zukunft ist ungewiss." },
  { id:"v370", lv:4, es:"el pasado", de:"die Vergangenheit", pos:"n", ex:"Eso es pasado.", exde:"Das ist Vergangenheit." },
  { id:"v371", lv:4, es:"el presente", de:"die Gegenwart", pos:"n", ex:"Vive el presente.", exde:"Lebe im Hier und Jetzt." },
  { id:"v372", lv:4, es:"la verdad", de:"die Wahrheit", pos:"n", ex:"Digo la verdad.", exde:"Ich sage die Wahrheit." },
  { id:"v373", lv:4, es:"la mentira", de:"die Lüge", pos:"n", ex:"Eso es una mentira.", exde:"Das ist eine Lüge." },
  { id:"v374", lv:4, es:"el miedo", de:"die Angst", pos:"n", ex:"Tengo miedo.", exde:"Ich habe Angst." },
  { id:"v375", lv:4, es:"la suerte", de:"das Glück (Zufall)", pos:"n", ex:"¡Buena suerte!", exde:"Viel Glück!" },
  { id:"v376", lv:4, es:"el éxito", de:"der Erfolg", pos:"n", ex:"Es un gran éxito.", exde:"Das ist ein großer Erfolg." },
  { id:"v377", lv:4, es:"el error", de:"der Fehler", pos:"n", ex:"Cometí un error.", exde:"Ich habe einen Fehler gemacht." },
  { id:"v378", lv:4, es:"la duda", de:"der Zweifel", pos:"n", ex:"Tengo una duda.", exde:"Ich habe einen Zweifel / eine Frage." },
  { id:"v379", lv:4, es:"la razón", de:"der Grund / recht", pos:"n", ex:"Tienes razón.", exde:"Du hast recht." },
  { id:"v380", lv:4, es:"el sentido", de:"der Sinn / das Gefühl", pos:"n", ex:"Tiene sentido.", exde:"Das ergibt Sinn." },
  { id:"v381", lv:4, es:"la manera", de:"die Art und Weise", pos:"n", ex:"No hay otra manera.", exde:"Es gibt keine andere Art." },
  { id:"v382", lv:4, es:"el ejemplo", de:"das Beispiel", pos:"n", ex:"Por ejemplo.", exde:"Zum Beispiel." },
  { id:"v383", lv:4, es:"el caso", de:"der Fall", pos:"n", ex:"En este caso, sí.", exde:"In diesem Fall ja." },
  { id:"v384", lv:4, es:"el objetivo", de:"das Ziel", pos:"n", ex:"Mi objetivo es hablar bien.", exde:"Mein Ziel ist, gut zu sprechen." },
  { id:"v385", lv:4, es:"el resultado", de:"das Ergebnis", pos:"n", ex:"El resultado es bueno.", exde:"Das Ergebnis ist gut." },
  { id:"v386", lv:4, es:"la decisión", de:"die Entscheidung", pos:"n", ex:"Es una decisión difícil.", exde:"Das ist eine schwere Entscheidung." },
  { id:"v387", lv:4, es:"la opinión", de:"die Meinung", pos:"n", ex:"En mi opinión…", exde:"Meiner Meinung nach…" },
  { id:"v388", lv:4, es:"el consejo", de:"der Rat", pos:"n", ex:"Un consejo: habla cada día.", exde:"Ein Tipp: Sprich jeden Tag." },
  { id:"v389", lv:4, es:"la experiencia", de:"die Erfahrung", pos:"n", ex:"Fue una buena experiencia.", exde:"Es war eine gute Erfahrung." },
  { id:"v390", lv:4, es:"el recuerdo", de:"die Erinnerung", pos:"n", ex:"Es un buen recuerdo.", exde:"Das ist eine schöne Erinnerung." },
  { id:"v391", lv:4, es:"la costumbre", de:"die Gewohnheit", pos:"n", ex:"Es una costumbre española.", exde:"Das ist eine spanische Gewohnheit." },
  { id:"v392", lv:4, es:"el ambiente", de:"die Atmosphäre", pos:"n", ex:"Hay buen ambiente.", exde:"Es herrscht gute Stimmung." },
  { id:"v393", lv:4, es:"peligroso", de:"gefährlich", pos:"adj", ex:"Es peligroso cruzar aquí.", exde:"Hier ist das Überqueren gefährlich." },
  { id:"v394", lv:4, es:"seguro", de:"sicher", pos:"adj", ex:"Estás seguro aquí.", exde:"Du bist hier sicher." },
  { id:"v395", lv:4, es:"posible", de:"möglich", pos:"adj", ex:"Es posible.", exde:"Das ist möglich." },
  { id:"v396", lv:4, es:"imposible", de:"unmöglich", pos:"adj", ex:"No es imposible.", exde:"Es ist nicht unmöglich." },
  { id:"v397", lv:4, es:"necesario", de:"notwendig", pos:"adj", ex:"Es necesario practicar.", exde:"Üben ist notwendig." },
  { id:"v398", lv:4, es:"libre", de:"frei", pos:"adj", ex:"¿Estás libre mañana?", exde:"Hast du morgen frei?" },
  { id:"v399", lv:4, es:"nervioso", de:"nervös", pos:"adj", ex:"Estoy nervioso.", exde:"Ich bin nervös." },
  { id:"v400", lv:4, es:"tranquilo", de:"ruhig", pos:"adj", ex:"Un pueblo tranquilo.", exde:"Ein ruhiges Dorf." },
  { id:"v401", lv:4, es:"ruidoso", de:"laut", pos:"adj", ex:"El bar es ruidoso.", exde:"Die Bar ist laut." },
  { id:"v402", lv:4, es:"limpio", de:"sauber", pos:"adj", ex:"La habitación está limpia.", exde:"Das Zimmer ist sauber." },
  { id:"v403", lv:4, es:"sucio", de:"schmutzig", pos:"adj", ex:"Los platos están sucios.", exde:"Das Geschirr ist schmutzig." },
  { id:"v404", lv:4, es:"rico", de:"lecker / reich", pos:"adj", ex:"Está muy rico.", exde:"Es ist sehr lecker." },
  { id:"v405", lv:4, es:"pobre", de:"arm", pos:"adj", ex:"Es un barrio pobre.", exde:"Es ist ein armes Viertel." },
  { id:"v406", lv:4, es:"fuerte", de:"stark", pos:"adj", ex:"Un café fuerte.", exde:"Ein starker Kaffee." },
  { id:"v407", lv:4, es:"débil", de:"schwach", pos:"adj", ex:"Me siento débil.", exde:"Ich fühle mich schwach." },
  { id:"v408", lv:4, es:"listo", de:"fertig / klug", pos:"adj", ex:"¿Estás listo?", exde:"Bist du fertig?" },
  { id:"v409", lv:4, es:"tonto", de:"dumm / albern", pos:"adj", ex:"No seas tonto.", exde:"Sei nicht albern." },
  { id:"v410", lv:4, es:"amable", de:"freundlich", pos:"adj", ex:"La gente es amable.", exde:"Die Leute sind freundlich." },
  { id:"v411", lv:4, es:"educado", de:"höflich", pos:"adj", ex:"Es muy educado.", exde:"Er ist sehr höflich." },
  { id:"v412", lv:4, es:"famoso", de:"berühmt", pos:"adj", ex:"Un pintor famoso.", exde:"Ein berühmter Maler." },
  { id:"v413", lv:4, es:"especial", de:"besonders", pos:"adj", ex:"Es un día especial.", exde:"Es ist ein besonderer Tag." },
  { id:"v414", lv:4, es:"normal", de:"normal", pos:"adj", ex:"Es normal estar nervioso.", exde:"Es ist normal, nervös zu sein." },
  { id:"v415", lv:4, es:"raro", de:"seltsam / selten", pos:"adj", ex:"Qué raro.", exde:"Wie seltsam." },
  { id:"v416", lv:4, es:"conseguir", de:"schaffen / bekommen", pos:"v", ex:"Consigo un billete.", exde:"Ich bekomme ein Ticket." },
  { id:"v417", lv:4, es:"intentar", de:"versuchen", pos:"v", ex:"Intento hablar español.", exde:"Ich versuche, Spanisch zu sprechen." },
  { id:"v418", lv:4, es:"lograr", de:"erreichen", pos:"v", ex:"Logré el objetivo.", exde:"Ich habe das Ziel erreicht." },
  { id:"v419", lv:4, es:"decidir", de:"entscheiden", pos:"v", ex:"Decido quedarme.", exde:"Ich entscheide mich zu bleiben." },
  { id:"v420", lv:4, es:"elegir", de:"wählen", pos:"v", ex:"Elige una opción.", exde:"Wähle eine Option." },
  { id:"v421", lv:4, es:"ofrecer", de:"anbieten", pos:"v", ex:"Te ofrezco un café.", exde:"Ich biete dir einen Kaffee an." },
  { id:"v422", lv:4, es:"aceptar", de:"annehmen", pos:"v", ex:"Acepto la invitación.", exde:"Ich nehme die Einladung an." },
  { id:"v423", lv:4, es:"rechazar", de:"ablehnen", pos:"v", ex:"Rechazo la oferta.", exde:"Ich lehne das Angebot ab." },
  { id:"v424", lv:4, es:"evitar", de:"vermeiden", pos:"v", ex:"Evito el tráfico.", exde:"Ich vermeide den Verkehr." },
  { id:"v425", lv:4, es:"permitir", de:"erlauben", pos:"v", ex:"No está permitido fumar.", exde:"Rauchen ist nicht erlaubt." },
  { id:"v426", lv:4, es:"prohibir", de:"verbieten", pos:"v", ex:"Prohíben nadar aquí.", exde:"Hier ist Schwimmen verboten." },
  { id:"v427", lv:4, es:"mejorar", de:"verbessern", pos:"v", ex:"Quiero mejorar mi español.", exde:"Ich möchte mein Spanisch verbessern." },
  { id:"v428", lv:4, es:"empeorar", de:"sich verschlechtern", pos:"v", ex:"El tiempo empeora.", exde:"Das Wetter wird schlechter." },
  { id:"v429", lv:4, es:"aumentar", de:"steigen / erhöhen", pos:"v", ex:"Los precios aumentan.", exde:"Die Preise steigen." },
  { id:"v430", lv:4, es:"bajar", de:"runtergehen / senken", pos:"v", ex:"Bajo las escaleras.", exde:"Ich gehe die Treppe runter." },
  { id:"v431", lv:4, es:"subir", de:"hochgehen / steigen", pos:"v", ex:"Subo al autobús.", exde:"Ich steige in den Bus." },
  { id:"v432", lv:4, es:"caer", de:"fallen", pos:"v", ex:"Se cae el vaso.", exde:"Das Glas fällt um." },
  { id:"v433", lv:4, es:"romper", de:"zerbrechen", pos:"v", ex:"Rompo un vaso.", exde:"Ich zerbreche ein Glas." },
  { id:"v434", lv:4, es:"arreglar", de:"reparieren / klären", pos:"v", ex:"Arreglo la bici.", exde:"Ich repariere das Fahrrad." },
  { id:"v435", lv:4, es:"construir", de:"bauen", pos:"v", ex:"Construyen una casa.", exde:"Sie bauen ein Haus." },
  { id:"v436", lv:4, es:"explicar", de:"erklären", pos:"v", ex:"¿Me lo explicas?", exde:"Erklärst du es mir?" },
  { id:"v437", lv:4, es:"preguntar", de:"fragen", pos:"v", ex:"Puedo preguntar algo.", exde:"Ich kann etwas fragen." },
  { id:"v438", lv:4, es:"contestar", de:"antworten", pos:"v", ex:"No contesta el teléfono.", exde:"Er/sie geht nicht ans Telefon." },
  { id:"v439", lv:4, es:"contar", de:"erzählen / zählen", pos:"v", ex:"Cuéntame qué pasó.", exde:"Erzähl mir, was passiert ist." },
  { id:"v440", lv:4, es:"mostrar", de:"zeigen", pos:"v", ex:"Muéstrame el camino.", exde:"Zeig mir den Weg." },
  { id:"v441", lv:4, es:"descubrir", de:"entdecken", pos:"v", ex:"Descubro una cafetería nueva.", exde:"Ich entdecke ein neues Café." },
  { id:"v442", lv:4, es:"inventar", de:"erfinden", pos:"v", ex:"No inventes historias.", exde:"Erfinde keine Geschichten." },
  { id:"v443", lv:4, es:"imaginar", de:"sich vorstellen", pos:"v", ex:"Imagina que viajamos.", exde:"Stell dir vor, wir reisen." },
  { id:"v444", lv:4, es:"soñar", de:"träumen", pos:"v", ex:"Sueño con viajar.", exde:"Ich träume vom Reisen." },
  { id:"v445", lv:4, es:"preocuparse", de:"sich Sorgen machen", pos:"v", ex:"No te preocupes.", exde:"Mach dir keine Sorgen." },
  { id:"v446", lv:4, es:"relajarse", de:"sich entspannen", pos:"v", ex:"Necesito relajarme.", exde:"Ich muss mich entspannen." },
  { id:"v447", lv:4, es:"divertirse", de:"Spaß haben", pos:"v", ex:"Nos divertimos mucho.", exde:"Wir haben viel Spaß." },
  { id:"v448", lv:4, es:"aburrirse", de:"sich langweilen", pos:"v", ex:"Me aburro en casa.", exde:"Ich langweile mich zu Hause." },
  { id:"v449", lv:4, es:"casarse", de:"heiraten", pos:"v", ex:"Se casan en junio.", exde:"Sie heiraten im Juni." },
  { id:"v450", lv:4, es:"nacer", de:"geboren werden", pos:"v", ex:"Nací en 1998.", exde:"Ich wurde 1998 geboren." },
  { id:"v451", lv:4, es:"morir", de:"sterben", pos:"v", ex:"Las flores mueren sin agua.", exde:"Blumen sterben ohne Wasser." },
  { id:"v452", lv:4, es:"crecer", de:"wachsen", pos:"v", ex:"Los niños crecen rápido.", exde:"Kinder wachsen schnell." },
  { id:"v453", lv:4, es:"cumplir", de:"erfüllen / Geburtstag haben", pos:"v", ex:"Cumplo treinta años.", exde:"Ich werde dreißig." },
  { id:"v454", lv:4, es:"prometer", de:"versprechen", pos:"v", ex:"Lo prometo.", exde:"Ich verspreche es." },
  { id:"v455", lv:4, es:"confiar", de:"vertrauen", pos:"v", ex:"Confío en ti.", exde:"Ich vertraue dir." },
  { id:"v456", lv:4, es:"dudar", de:"zweifeln", pos:"v", ex:"Dudo que llueva.", exde:"Ich bezweifle, dass es regnet." },
  { id:"v457", lv:4, es:"agradecer", de:"danken", pos:"v", ex:"Te lo agradezco.", exde:"Ich danke dir dafür." },
  { id:"v458", lv:4, es:"felicitar", de:"gratulieren", pos:"v", ex:"Te felicito.", exde:"Ich gratuliere dir." },
  { id:"v459", lv:4, es:"invitar", de:"einladen", pos:"v", ex:"Te invito a cenar.", exde:"Ich lade dich zum Abendessen ein." },
  { id:"v460", lv:4, es:"reunirse", de:"sich treffen", pos:"v", ex:"Nos reunimos el viernes.", exde:"Wir treffen uns am Freitag." },
  { id:"v461", lv:4, es:"el puente", de:"die Brücke", pos:"n", ex:"Cruzamos el puente.", exde:"Wir überqueren die Brücke." },
  { id:"v462", lv:4, es:"el río", de:"der Fluss", pos:"n", ex:"El río es ancho.", exde:"Der Fluss ist breit." },
  { id:"v463", lv:4, es:"el bosque", de:"der Wald", pos:"n", ex:"Paseamos por el bosque.", exde:"Wir spazieren durch den Wald." },
  { id:"v464", lv:4, es:"el cielo", de:"der Himmel", pos:"n", ex:"El cielo está gris.", exde:"Der Himmel ist grau." },
  { id:"v465", lv:4, es:"la nube", de:"die Wolke", pos:"n", ex:"Hay muchas nubes.", exde:"Es gibt viele Wolken." },
  { id:"v466", lv:4, es:"el viento", de:"der Wind", pos:"n", ex:"Hace viento.", exde:"Es ist windig." },
  { id:"v467", lv:4, es:"la nieve", de:"der Schnee", pos:"n", ex:"Nieva en invierno.", exde:"Im Winter schneit es." },
  { id:"v468", lv:4, es:"el verano", de:"der Sommer", pos:"n", ex:"En verano hace calor.", exde:"Im Sommer ist es heiß." },
  { id:"v469", lv:4, es:"el invierno", de:"der Winter", pos:"n", ex:"En invierno nieva.", exde:"Im Winter schneit es." },
  { id:"v470", lv:4, es:"la primavera", de:"der Frühling", pos:"n", ex:"La primavera es bonita.", exde:"Der Frühling ist schön." },
  { id:"v471", lv:4, es:"el otoño", de:"der Herbst", pos:"n", ex:"En otoño caen las hojas.", exde:"Im Herbst fallen die Blätter." },
  { id:"v472", lv:4, es:"la fiesta", de:"das Fest / die Party", pos:"n", ex:"Hay una fiesta el sábado.", exde:"Am Samstag ist eine Party." },
  { id:"v473", lv:4, es:"el regalo", de:"das Geschenk", pos:"n", ex:"Un regalo para ti.", exde:"Ein Geschenk für dich." },
  { id:"v474", lv:4, es:"la boda", de:"die Hochzeit", pos:"n", ex:"Voy a una boda.", exde:"Ich gehe zu einer Hochzeit." },
  { id:"v475", lv:4, es:"el cumpleaños", de:"der Geburtstag", pos:"n", ex:"¡Feliz cumpleaños!", exde:"Alles Gute zum Geburtstag!" },
  { id:"v476", lv:4, es:"la Navidad", de:"Weihnachten", pos:"n", ex:"En Navidad viajo.", exde:"An Weihnachten reise ich." },
  { id:"v477", lv:4, es:"el año nuevo", de:"das neue Jahr", pos:"n", ex:"Feliz año nuevo.", exde:"Frohes neues Jahr." },
  { id:"v478", lv:4, es:"la reunión", de:"das Treffen / Meeting", pos:"n", ex:"Tengo una reunión.", exde:"Ich habe ein Meeting." },
  { id:"v479", lv:4, es:"la cita", de:"der Termin / das Date", pos:"n", ex:"Tengo una cita a las cinco.", exde:"Ich habe um fünf einen Termin." },
  { id:"v480", lv:4, es:"el plan", de:"der Plan", pos:"n", ex:"¿Cuál es el plan?", exde:"Was ist der Plan?" },
  { id:"v481", lv:4, es:"el camino", de:"der Weg", pos:"n", ex:"Este es el camino.", exde:"Das ist der Weg." },
  { id:"v482", lv:4, es:"la entrada", de:"der Eingang / die Eintrittskarte", pos:"n", ex:"¿Dónde está la entrada?", exde:"Wo ist der Eingang?" },
  { id:"v483", lv:4, es:"la salida", de:"der Ausgang / die Abfahrt", pos:"n", ex:"La salida es a las ocho.", exde:"Die Abfahrt ist um acht." },
  { id:"v484", lv:4, es:"el horario", de:"der Fahrplan / die Öffnungszeiten", pos:"n", ex:"Mira el horario.", exde:"Schau in den Fahrplan." },
  { id:"v485", lv:4, es:"retrasado", de:"verspätet", pos:"adj", ex:"El tren va retrasado.", exde:"Der Zug hat Verspätung." },
  { id:"v486", lv:4, es:"puntual", de:"pünktlich", pos:"adj", ex:"El vuelo no es puntual.", exde:"Der Flug ist nicht pünktlich." },
  { id:"v487", lv:4, es:"gratis", de:"kostenlos", pos:"adj", ex:"La entrada es gratis.", exde:"Der Eintritt ist frei." },
  { id:"v488", lv:4, es:"incluido", de:"inklusive", pos:"adj", ex:"El desayuno está incluido.", exde:"Das Frühstück ist inklusive." },
  { id:"v489", lv:4, es:"disponible", de:"verfügbar", pos:"adj", ex:"¿Hay mesa disponible?", exde:"Ist ein Tisch frei?" },
  { id:"v490", lv:4, es:"completo", de:"ausgebucht / vollständig", pos:"adj", ex:"El hotel está completo.", exde:"Das Hotel ist ausgebucht." },
  { id:"v491", lv:4, es:"a menudo", de:"oft", pos:"phr", ex:"Viajo a menudo.", exde:"Ich reise oft." },
  { id:"v492", lv:4, es:"de vez en cuando", de:"ab und zu", pos:"phr", ex:"Como carne de vez en cuando.", exde:"Ich esse ab und zu Fleisch." },
  { id:"v493", lv:4, es:"enseguida", de:"sofort", pos:"adv", ex:"Vengo enseguida.", exde:"Ich komme sofort." },
  { id:"v494", lv:4, es:"apenas", de:"kaum", pos:"adv", ex:"Apenas entiendo.", exde:"Ich verstehe kaum etwas." },
  { id:"v495", lv:4, es:"quizá", de:"vielleicht", pos:"adv", ex:"Quizá llueva mañana.", exde:"Vielleicht regnet es morgen." },
  { id:"v496", lv:4, es:"tal vez", de:"vielleicht", pos:"phr", ex:"Tal vez vaya.", exde:"Vielleicht gehe ich." },
  { id:"v497", lv:4, es:"en absoluto", de:"überhaupt nicht", pos:"phr", ex:"No me gusta en absoluto.", exde:"Das mag ich überhaupt nicht." },
  { id:"v498", lv:4, es:"desde luego", de:"allerdings / natürlich", pos:"phr", ex:"Desde luego que sí.", exde:"Aber selbstverständlich." },
  { id:"v499", lv:4, es:"dar igual", de:"egal sein", pos:"phr", ex:"Me da igual.", exde:"Ist mir egal." },
  { id:"v500", lv:4, es:"tener ganas de", de:"Lust haben auf", pos:"phr", ex:"Tengo ganas de viajar.", exde:"Ich habe Lust zu reisen." }
];
